# Generated by Django 4.2.30 on 2026-09-03 07:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='cv',
            field=models.FileField(upload_to='cvs/careers/', validators=[core.validators.validate_pdf_extension, core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='cv',
            field=models.FileField(upload_to='cvs/internships/', validators=[core.validators.validate_pdf_extension, core.validators.validate_file_size]),
        ),
    ]
