# Generated by Django 4.2.30 on 2026-09-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careerapplication_cv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internshipapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
