# Generated by Django 4.2.30 on 2026-09-23 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_hrnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('breakdown', models.JSONField(blank=True, default=list, help_text="List of categories and percentages e.g. [{'name': 'Frontend', 'percentage': 25}]")),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('requirements_submitted', 'Requirements Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=50)),
                ('employee_requirements', models.TextField(blank=True, help_text="Employee's requirements/notes for completing the task")),
                ('employee_comments', models.TextField(blank=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
