# Generated by Django 4.2.30 on 2026-09-27 03:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_essnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='hr/cvs/', validators=[core.validators.validate_pdf_extension, core.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
    ]
