# Generated by Django 4.2.30 on 2026-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_cv_file_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating out of 10', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('requirements_submitted', 'Requirements Submitted'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=50),
        ),
    ]
