# Generated by Django 4.2.30 on 2026-09-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_task_priority_task_rating_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month/year requested (select 1st of month)')),
                ('reason', models.TextField(blank=True, help_text='Reason for requesting this payslip')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('generated', 'Generated')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_requests', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
