# Generated by Django 4.2.30 on 2026-09-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_paysliprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysliprequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
    ]
