# Generated by Django 4.2.30 on 2026-09-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_paysliprequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysliprequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional supporting document', null=True, upload_to='payslip_requests/'),
        ),
    ]
