# Generated by Django 4.2.30 on 2026-09-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_paysliprequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_file',
            field=models.FileField(blank=True, help_text='File uploaded by HR/Manager', null=True, upload_to='tasks/assigned/'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_file',
            field=models.FileField(blank=True, help_text='File uploaded by Employee', null=True, upload_to='tasks/submitted/'),
        ),
    ]
