# Generated by Django 4.2.30 on 2026-09-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='approach_text',
            field=models.TextField(blank=True, help_text="Text for 'Our Approach' section"),
        ),
        migrations.AddField(
            model_name='program',
            name='challenge_text',
            field=models.TextField(blank=True, help_text="Text for 'The Challenge' section"),
        ),
        migrations.AddField(
            model_name='program',
            name='interventions',
            field=models.JSONField(blank=True, default=list, help_text="List of interventions e.g. [{'title': '...', 'description': '...'}]"),
        ),
        migrations.AddField(
            model_name='program',
            name='quote_author',
            field=models.CharField(blank=True, help_text='Author of the quote', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Inspirational quote text'),
        ),
        migrations.AddField(
            model_name='program',
            name='stats',
            field=models.JSONField(blank=True, default=list, help_text="List of stats e.g. [{'value': '1.2M', 'label': 'Trees'}]"),
        ),
    ]
