# Generated by Django 4.2.30 on 2026-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_approach_text_program_challenge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donors_count',
            field=models.IntegerField(default=0),
        ),
    ]
