# Generated by Django 4.2.30 on 2026-10-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
